# Generated by Django 3.2 on 2023-04-29 20:46

import django.core.validators
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Неверно введено имя', regex='^[\\w.@+-]+\\Z'), users.utils.validate_username_me], verbose_name='username'),
        ),
    ]
